@startuml

Class Account {
  +String accountId (PK)
  +String name
  +String role
  +String password
}

Class Bid {
  +String bidID (PK)
  +String accountId (FK)
  +Double price
  +Long rank
  +LocalDateTime time
  +String bwicID
}

class BidRank {
  +String bidID (FK,PK)
  +String accountId
  +Double price
  +LocalDateTime time
  +String bwicID
}

Class BWIC {
  +String bwicID (PK)
  +String boundID (FK)
  +Double size
  +Double startPrice
  +LocalDateTime startTime
  +LocalDateTime dueTime
  +Long times
}

Class Bond {
  +String bondID (FK)
  +String cusip 
  +String issuer
  +String rating
  +Double coupon
  +LocalDateTime maturityDate
}

Class AccountService {
  +void login(String accountId, String password)
  +Account findById(String accountId)
  +List<BWIC> recommendBWIC(String accountId)
}

Class BidService {
  +Bid createBid(String cusip, Double price)
  +void updateRank(String bwicId, Long newRank)  #insert Bid, update BidRank
  +Long getRank(String bidId)
  +List<Bid> bidHistoryRecord(String accountId)
}

Class BWICService {
  +BWIC createBWIC(BWIC bwic)
  +Long getRank(String accountId, String bidId)  #获得当前用户的rank
  +boolean isActive(String bwicId)
  +List<BWIC> bwicHistoryRecord(String accountId)
  +Double getPrice(String bwicId)
}

AccountService --> Account : Uses
BidService --> Bid : Uses
BidService --> BidRank : Uses
BWICService --> BWIC : Uses
BidService --> BWICService : Calls
BWICService --> BidService : Calls
Bid --> BWIC : Relies on
Bid --> Account : Relies on
BidRank --> Bid : Relies on
BWIC --> Bond : Relies on
AccountService --> BWICService : Calls

@enduml
