spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding_bid?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: lyy020314

  jpa:
    show-sql: true