spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding_bid?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jpa:
    show-sql: true

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848