spring:
  datasource:
    url: jdbc:mysql://47.108.72.83:3306/ebidding_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: cq-team
    password: cq-team!
  jpa:
    show-sql: false
