spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1704Mysql
 #   password: lyy020314
#  password: root


  jpa:
    show-sql: true