spring:
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/accounts/**
        - id: bid_service
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1/bids/**
          filters:
            JwtFilter