spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding_bwic?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#   password: root
    password: lyy020314

    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848

  jpa:
    show-sql: true

ebidding:
  account-endpoint: localhost:8001
  bid-endpoint: localhost:8002
  bwic-endpoint: localhost:8003