spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebidding_bwic?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    show-sql: true